services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: genbi_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - legal-net


networks:
  legal-net:
    driver: bridge
